# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: test-java-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 设置jdk11环境
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: 编译构建
      run: mvn clean package -DskipTest=true
    - name: 列出文件
      run: ls target/*.jar
    - uses: actions/checkout@v2
    - name: 构建镜像
      run: docker build -t test:$(date +%s) .
    - name: 查看镜像
      run: docker images
